### ISSUE TITLE
Build failure due to gala dependency issue

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#10]
Building the current development brnch depends on a gala header that is not installed when doing a "make install" for gala:

g++ -DHAVE_CONFIG_H -I. -I..   -I. -DNDEBUG  -fprofile-generate -Os -march=native -g -O2 -std=c++11 -MT tdecomp_profile-tdecomp.o -MD -MP -MF .deps/tdecomp_profile-tdecomp.Tpo -c -o tdecomp_profile-tdecomp.o `test -f 'tdecomp.cc' || echo './'`tdecomp.cc
In file included from tdecomp.cc:50:0:
twh.h:87:10: fatal error: gala/examples/ssg32i.h: Datei oder Verzeichnis nicht gefunden
 #include <gala/examples/ssg32i.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Philipp

**Comment by felix-salfelder** [comment]
should be fixed now. also, CI now tests gala "make install".

**Comment by spth** [comment]
This one is fixed, so the build runs into the next one:

g++ -DHAVE_CONFIG_H -I. -I..   -I. -DNDEBUG  -fprofile-generate -Os -march=native -g -O2 -std=c++11 -MT tdecomp_profile-tdecomp.o -MD -MP -MF .deps/tdecomp_profile-tdecomp.Tpo -c -o tdecomp_profile-tdecomp.o `test -f 'tdecomp.cc' || echo './'`tdecomp.cc
In file included from /usr/local/include/gala/td.h:25:0,
                 from /usr/local/include/gala/examples/ssg32i.h:32,
                 from twh.h:87,
                 from tdecomp.cc:50:
/usr/local/include/gala/examples/ssg16ia.h:7:10: fatal error: alloc.hpp: Datei oder Verzeichnis nicht gefunden
 #include "alloc.hpp"
          ^~~~~~~~~~~
compilation terminated.
Makefile:540: die Regel für Ziel „tdecomp_profile-tdecomp.o“ scheiterte

Philipp

**Comment by felix-salfelder** [comment]
sorry. yes there was another problem in between...
