### ISSUE TITLE
Rename pytdlib to pytreedec for consistency?

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#17]
The library is called treedec, but the python stuff uses pytdlib. Should it be renamed to pytreedec?

Philipp

**Comment by felix-salfelder** [comment]
other python packages do not have "py" in their name, unless the name is very short (num, sym, sci). but in these cases, "py" is the suffix... how about just "treedec"?

or just reserve that name for the (almost finished) rewrite, and leave it like that.

**Comment by spth** [comment]
Just treedec seems fine. But I don't know much about python naming conventions or python(s) in general. If there is a rewrite happening, it might make sense to not do the rename now.

Philipp

**Comment by felix-salfelder** [comment]
its all 'treedec' now, except the python module name. the rewrite will be called 'treedec'.
