### ISSUE TITLE
Minimum version of C++ required?

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#2]
The README should probably state the minimum version of C++ required for tdlib.
AFAIR, Felix said that it needs a relatively recent version, but I don't remember if it is C++11, C++14 or C++17.

Philipp

**Comment by felix-salfelder** [comment]
hi Philipp

yes, it should be in the README.

the upcoming development snapshot will make use of C++11 features. C++>11 will not be required in the near future.

thanks

**Comment by spth** [comment]
OK; we will probably raise the minimum MSVC++ version for SDCC to MSVC++ 2015, which supports nearly all of C++ 11 (and some bits of C++14 and C++17), so C++11 i sfine for me

Philipp

**Comment by felix-salfelder** [comment]
that sounds good.
