### ISSUE TITLE
treedec::thorup::get_elimord() type issue

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#20]
get_elimord() tries to use a reference to std::vector<unsigned> as a reference to std::list<unsigned>.
Compilation fails with GCC 8.1:

~~~~
/usr/local/include/treedec/thorup.hpp: In member function ‘const std::__cxx11::list<unsigned int>& treedec::thorup<G, config>::get_elimord() const’:
/usr/local/include/treedec/thorup.hpp:390:10: error: invalid initialization of reference of type ‘const std::__cxx11::list<unsigned int>&’ from expression of type ‘const std::vector<unsigned int>’
   return _o;
~~~~

Philipp

**Comment by felix-salfelder** [comment]
gcc 8 seems to be more picky about dead code. i changed it and added a test.

was that the only issue?

thanks!

**Comment by spth** [comment]
Yes, this was the only issue. Thanks for the quick fix!

Philipp
