### ISSUE TITLE
Build fails due to header path issue

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#22]
I tried building current master on Debian GNU/Linux. On "make", I get:

~~~~
In file included from tdecomp.cc:53:0:
twh.h:78:10: fatal error: tdlib/graph_traits.hpp: Datei oder Verzeichnis nicht gefunden
 #include <tdlib/graph_traits.hpp>
~~~~

Philipp

**Comment by felix-salfelder** [comment]
this is fixed in develop

**Comment by felix-salfelder** [comment]
weird. line 87 in examples/twh.h (as of 819a01ffa5) reads
    
    #include <treedec/graph_traits.hpp>

it has been changed in 819a01ffa5117.

and there is only one twh.h... can you please recheck?

**Comment by felix-salfelder** [comment]
sorry, in b7b72d4eb (edited the previous post)

**Comment by spth** [comment]
Ah I didn't notice that the error message referred to a different header this time:

~~~~
In file included from twh.h:90:0,
                 from tdecomp.cc:53:
/usr/local/include/gala/examples/ssg32i.h:31:10: fatal error: tdlib/graph_traits.hpp: Datei oder Verzeichnis nicht gefunden
 #include <tdlib/graph_traits.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
~~~~

But an update of gala fixed that. Sorry for the noise.

Philipp

**Comment by felix-salfelder** [comment]
On Mon, May 21, 2018 at 07:34:40AM -0700, Philipp Klaus Krause wrote:
> But an update of gala fixed that. Sorry for the noise.

no worries.

thanks for the testing!
