### ISSUE TITLE
"make check" fails to link target "inline" on Debian GNU/Hurd

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#23]
On "make check" for current master, it complains about multiple definitions for treedec::nice::min(unsigned int, unsigned int).

Philipp

**Comment by felix-salfelder** [comment]
thanks for your report.

does this also apply to "develop"? or is it related to HURD? (sorry about the confusion)

**Comment by spth** [comment]
I didn't try develop yet. And due to bug #22, I couldn't try on Debian GNU/Linux (with gala), so for now, I only tested on Hurd (without gala).

Philipp

**Comment by felix-salfelder** [comment]
On Mon, May 21, 2018 at 06:35:50AM -0700, Philipp Klaus Krause wrote:
> I didn't try develop yet. And due to bug #22, I couldn't try on Debian
> GNU/Linux (with gala), so for now, I only tested on Hurd (without
> gala).

thanks. #22 seems fixed in develop.

**Comment by spth** [comment]
Works for me in develop.
