### ISSUE TITLE
treedec uses deprecated tr1 header

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#25]
treedec includes the deprecated tr1/utility from src/iter.hpp.

On OpenBSD 6.3, this file does not seem to be available.

AFAIK all library parts from the old TR1 have been deprecated at least since C++14, with C++11 providing equivalent functionality in the standard library. And treedec already depends on C++11, so why use this old header instead of whichever header provides equivalent functionality in C++11?

Philipp

**Comment by felix-salfelder** [comment]
thanks it looks to be the only one.

fixed in develop
