### ISSUE TITLE
Do not require vertex lists to be std::set<…>

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#29]
treedec currently seems to mostly require the vertex lists of the input graphs to be boost::setS, i.e. std::set<…>.

Would it be possible, and useful for speed to allow other containers?

thorup works with boost::vecS, i.e. std::vector<…>, too. But at least ex17 and PP_FI_TM don't.

Philipp

**Comment by felix-salfelder** [comment]
On Thu, Sep 27, 2018 at 01:17:33AM -0700, Philipp Klaus Krause wrote:
> treedec currently seems to mostly require the vertex lists of the
> input graphs to be boost::setS, i.e. std::set<…>.

there is old code around, this will have to be done step by step. yes
this is important.

> Would it be possible, and useful for speed to allow other containers?
> thorup works with boost::vecS, i.e. std::vector<…>, too. But at least ex17 and PP_FI_TM don't.

FWIW, examples/tdecomp runs some of these algorithms (including ex17 and
an experimenal PPFITM) and uses vectors exclusively, when using gala.
all the newer code has been developped and tested using gala as backend.
gala is somewhat simpler than boost::graph (no property maps), but much
more flexible (choose your own containers).

note that normally, replacing the containers alone does not work,
although std::set vs boost::flat_set can be an exception. need to be
really careful with this.. many of the algorithms had to reformulated to
make vectors work at all.

i think there is a bug that currently prevents the compilation of
algorithms using boost::adjacency_list with edge vectors, it seems
related to property maps. i will try and fix it, but i cant give a
timeline right now.

**Comment by felix-salfelder** [comment]
fixed in develop
