### ISSUE TITLE
get_pos macro

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#3]
tdlib uses a macro named get_pos, which seems a bad choice given the risk of name conflicts.

Indeed, current boost uses functions named get_pos, resulting in tdlib not working with current boost:

~~~~
In file included from /usr/include/boost/container/detail/flat_tree.hpp:30:0,
                 from /usr/include/boost/container/flat_set.hpp:29,
                 from ../../../../lib/src/exact_cutset.hpp:40,
                 from ../../../../lib/src/combinations.hpp:56,
                 from SDCClospre.cc:25:
/usr/include/boost/container/vector.hpp:197:27: error: macro "get_pos" requires 2 arguments, but only 1 given
       while(this->get_pos() == size_type(-1)){
~~~~

Philipp

**Comment by felix-salfelder** [comment]
no, it's just work in progress in the development branch

    #ifndef get_pos
    // HACK, cleanup later
    #define get_pos(a,b) ( boost::get(boost::vertex_index, b, a) )
    #endif

it must be substituted everywhere, then the define will be removed.

will try asap

**Comment by spth** [comment]
get_pos is in the master branch, too.

Philipp

**Comment by felix-salfelder** [comment]
yikes. i thought master was still using the (broken) function.

thanks for pointing that out

**Comment by felix-salfelder** [comment]
should be fixed now, in master and development

**Comment by spth** [comment]
When ich td_combinations verwende, ist get_pos immer noch irgendwo, wo ein boost header inclusider wird, definiert. Sowohl in development als auch in master.

Philipp

**Comment by spth** [comment]
With the latest commits I now no longer see the error.

Philipp

**Comment by felix-salfelder** [comment]
phew. thanks Philipp `:)`
