### ISSUE TITLE
configure fails to detect cython 3

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#32]
configure only finds cython for Python 2, not cython for Python 3. Example from a Debian GNU/Linuxtesting system with cython3 package and no python2 installed:

checking for python3... /usr/bin/python3
checking for python3 version... 3.7
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.7/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib/python3.7/site-packages
checking for cython... no
configure: error: cannot find cython.

**Comment by felix-salfelder** [comment]
On Fri, Mar 06, 2020 at 07:49:22AM -0800, Philipp Klaus Krause wrote:
> configure: error: cannot find cython.

Please, could you check if it works and close the issue?

$ configure CYTHON=cython3

**Comment by spth** [comment]
Works for me. Thanks.

**Comment by spth** [comment]
I'd suggest to document CYTHON somewhere. Maybe ./configure --help should mention it?

**Comment by felix-salfelder** [comment]
> Maybe ./configure --help should mention it?

done, thanks
