### ISSUE TITLE
configure should check for more boost libraries

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#33]
On a system without boost thread and system libraries installed, configure passes, but make fails:

/usr/bin/ld: cannot find -lboost_thread
/usr/bin/ld: cannot find -lboost_system

**Comment by felix-salfelder** [comment]
On Fri, Mar 06, 2020 at 07:51:03AM -0800, Philipp Klaus Krause wrote:
> On a system without boost thread and system libraries installed, configure passes, but make fails:
> 
> /usr/bin/ld: cannot find -lboost_thread
> /usr/bin/ld: cannot find -lboost_system

Please, could you check if it works and close the issue?

configure should complain now if these are not available.

**Comment by spth** [comment]
Works for me. Thanks.
