### ISSUE TITLE
exact_decomposition_cutset endlessly searches tree-width decomposition

### ISSUE THREAD

**Issue by bazillo** [freetdi/tdlib#39]
`exact_decomposition_cutset` is searching tree-witdth decomposition of some graphs endlessly on Windows and getting SEGFAULT on Ubuntu. We met this problem searching tree-width decomposition of [grid n by n](https://pastebin.com/sFrgvNH7) (n > 7).

**Comment by llarisch** [comment]
We will have a look into this, but n x n grids are the best way to fool this algorithm - there are no valueable separators in such a graph. Please have a look into the pace17 algorithm. 

If you still want to use the cutset algo, please provide an example - python or c++ call code.

**Comment by elproblema** [comment]
https://pastebin.com/sFrgvNH7 link to call code

**Comment by felix-salfelder** [comment]
On Sat, Jul 03, 2021 at 01:49:50PM -0700, elproblema wrote:
> https://pastebin.com/sFrgvNH7 link to call code

Thanks.

I am running out of memory for the 8x8 grid. The program seems to produce
correct decompositions for grids up to 7x7, so this is about as far as we get.
(Please close if you agree.)

You can probably modify your program to run ex17 instead, as Lukas
suggests.  Or try tdecomp on a .gr dump.

$ cat 10x10.gr
p tw 100 180
1 2
2 3
3 4
4 5
5 6
[..]
$ /usr/bin/time -v examples/tdecomp --ex17 < 10x10.gr  | grep -v incomplete > 10x10.td
[..]
Elapsed (wall clock) time (h:mm:ss or m:ss): 3:09.29
[..]
$ examples/td-validate 10x10.gr 10x10.td
valid
$ grep ^s 10x10.td
s td 72 11 100
