### ISSUE TITLE
gala dependency

### ISSUE THREAD

**Issue by pca006132** [freetdi/tdlib#45]
When building without gala, the tests won't build:
```
fill_in0.cpp:10:10: fatal error: gala/cbset.h: No such file or directory
   10 | #include <gala/cbset.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:966: fill_in0.o] Error 1
make[3]: *** Waiting for unfinished jobs....
fill_in1.cpp:10:10: fatal error: gala/cbset.h: No such file or directory
   10 | #include <gala/cbset.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:966: fill_in1.o] Error 1
fill_in2.cpp:10:10: fatal error: gala/cbset.h: No such file or directory
   10 | #include <gala/cbset.h>
      |          ^~~~~~~~~~~~~~
```

**Comment by felix-salfelder** [comment]
On Wed, Jul 06, 2022 at 01:25:14AM -0700, pca006132 wrote:
> When tdlib is built with gala dependency, it reports the following errors when building examples:

Thanks for the report.

It seems to have worked a couple of days ago [1]... and it does for me.

Happy to look into it more. Please provide a few more details. Eg.
which branches, which boost version or which commands did you use, on
what system?

[1] https://github.com/freetdi/tdlib/issues/43

**Comment by pca006132** [comment]
> It seems to have worked a couple of days ago [1]... and it does for me.

~~Sorry I was modifying the makefile by removing the examples directory to make it compile at that time, as I was rushing for a project. Just found some time to report the problems properly.~~

~~I'm using the develop branch of both repos (gala: a9a42400ef92a685da5eb2cf2e3608bd75e78d19, tdlib: bc8136530aa3de5f2e36dab3c2ee6eafbb6c653a), compiled with gcc 11.3.0, boost 1.55, on NixOS.~~

Commands:
```
./bootstrap
./configure --with-gala --prefix=$out
make check -j8 DIST=true
```

OK It seems that I got the wrong version of boost, compiled with 1.77. I'm sorry for that.

**Comment by felix-salfelder** [comment]
On Wed, Jul 06, 2022 at 01:53:43AM -0700, pca006132 wrote:
> I'm using the develop branch of both repos (gala: a9a42400ef92a685da5eb2cf2e3608bd75e78d19, tdlib: bc8136530aa3de5f2e36dab3c2ee6eafbb6c653a), compiled with gcc 11.3.0, boost 1.55, on NixOS.

I suspect boost 1.55 is too old. Could you try a newer one by any
chance?

I only have 1.74 here, but I remember there were some issues with older
boost.

cheers
felix

**Comment by felix-salfelder** [comment]
seems to work now
