### ISSUE TITLE
REGISTER_GRAPH_WITH_BUNDLED_BAGS ;

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#5]
The README uses

REGISTER_GRAPH_WITH_BUNDLED_BAGS(my_td_type, bag);

tdlib itself sometime uses 

REGISTER_GRAPH_WITH_BUNDLED_BAGS(my_td_type, bag);

sometimes

REGISTER_GRAPH_WITH_BUNDLED_BAGS(my_td_type, bag)

If there should be a ';', the macro should be changed to require it (i.e. remove the last ';', so the compiler complains when the ';' after the macro use is missing. If the ';' should not be there, the documentation and uses in tdlib should be changed.

Philipp

**Comment by spth** [comment]
I'll see if I can come up with a proposal as a pull request.

Philipp

**Comment by spth** [comment]
Done: https://github.com/freetdi/tdlib/pull/8

Philipp

**Comment by felix-salfelder** [comment]
void TDLIB_DUMMY_FUNCTION_DECLARATION(void) 

thanks for the fix. i had this idea too. but i think it is misleading, as there is no function involved here.

do you know any other code where traits are injected with a macro? i would guess that `ADD_TREEDEC_TRAITS(t, b)` will be a better name.

(if it fixes a compiler error for you, i can still merge it like that, for now)

**Comment by spth** [comment]
Well, so far I only tested with GCC. Since I don't use -Werror, it only fixes warnings for me, not errors. But other compilers might be more strict on this issue.

I have no idea on the macro name. My only complaint about the macro is that it fixes the name of the data type used for tree-decompositions. Previously different optimizations in SDCC uses differently-named types, which "just worked" with templates, but requires extra effort with a macro.

Philipp

**Comment by felix-salfelder** [comment]
this is now working as intended in many cases. more tests have been added..,
